controllers:
    resource: ../src/Controller/
    type: attribute
app_forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityController::forgotPassword
app_details_trick:
    path: /details
    controller: App\Controller\SecurityController::detailsTrick